const CONNECT = 'CONNECT'
const GET_RANDOM = 'GET_RANDOM'
const GET_FULL = 'GET_FULL'
const GET_COMPLETE = 'GET_COMPLETE'
const GET_CUSTOM = 'GET_CUSTOM'
const POST_FULL = 'POST_FULL'
const POST_CUSTOM = 'POST_CUSTOM'

export default {
  CONNECT,
  GET_RANDOM,
  GET_FULL,
  GET_COMPLETE,
  GET_CUSTOM,
  POST_FULL,
  POST_CUSTOM
};