const CAPABILITIES = 'CAPABILITIES'
const GET_RANDOM = 'GET_RANDOM'
const GET_FULL = 'GET_FULL'
const GET_COMPLETE = 'GET_COMPLETE'
const GET_CUSTOM = 'GET_CUSTOM'
const POST_FULL = 'POST_FULL'
const POST_CUSTOM = 'POST_CUSTOM'
const API_CALL_SUCCESS = 'API_CALL_SUCCESS'
const API_CALL_FAILURE = 'API_CALL_FAILURE'
const CAP_SUCCESS = 'CAP_SUCCESS'
const CAP_FAILURE = 'CAP_FAILURE'
export default CAPABILITIES
export {
  CAPABILITIES,
  GET_RANDOM,
  GET_FULL,
  GET_COMPLETE,
  GET_CUSTOM,
  POST_FULL,
  POST_CUSTOM,
  API_CALL_SUCCESS,
  API_CALL_FAILURE,
  CAP_FAILURE,
  CAP_SUCCESS
};